[package]
name = "salsaa"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.12.0"
rokoko = { git = "https://github.com/lattice-arguments/rokoko.git", rev = "2bf7c9d6ccd7af54307769e4df6d01c7ef7b5b9f" }

[features]
default = ["p-26", "incomplete-rexl"]

incomplete-rexl = ["rokoko/incomplete-rexl"]
unsafe-sumcheck = ["rokoko/unsafe-sumcheck"]
debug-hardness = ["rokoko/debug-hardness"]
debug-decomp = ["rokoko/debug-decomp"]
parallel = []

p-30 = ["rokoko/p-30"]
p-26 = ["rokoko/p-26"]
p-28 = ["rokoko/p-28"]
